CREATE TABLE TipoCargo (
  id integer NOT NULL,
  duracao integer DEFAULT NULL,
  nomeCargo varchar(255) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (nomeCargo)
);

CREATE TABLE Cargo (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  unidade varchar(100) NOT NULL,
  tipo_id integer NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (tipo_id) REFERENCES TipoCargo(id)
);

CREATE TABLE Pessoa (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  cpf varchar(255) NOT NULL,
  nome varchar(100) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE Mandato (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  dataFim date NOT NULL,
  dataInicio date NOT NULL,
  cargo_id integer NOT NULL,
  pessoa_id integer NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (cargo_id) REFERENCES Cargo (id),
  FOREIGN KEY (pessoa_id) REFERENCES Pessoa (id)
);

CREATE SEQUENCE LOW_CARDINALITY_SEQUENCE START WITH 1 INCREMENT BY 1;